image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

before_build:
  - choco install opencover.portable
  - choco install codecov
  - dotnet restore

build:
  project: Nancy.Serilog.Simple.sln

test_script:
  - OpenCover.Console.exe -oldstyle -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full Nancy.Serilog.Simple.Tests\Nancy.Serilog.Simple.Tests.csproj" -filter:"+[Nancy.Serilog.Simple*]* -[Nancy.Serilog.Simple.Tests*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t %CODECOV_TOKEN%

after_test:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: Nancy.Serilog.Simple\bin\Release\netstandard2.0\Nancy.Serilog.Simple.dll
    name: Nancy.Serilog.Simple.dll
  - path: Nancy.Serilog.Simple\bin\Release\Nancy.Serilog.Simple.%version%.nupkg
    name: Nancy.Serilog.Simple.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: csyDlyeSjDmdYAQ/PK0GYNZ4ofK/yC6vd5ZLPnG2TgujmrAW7fUiQxjDVOWD4XAX
